### ISSUE TITLE
move tests back to ava and linux env

### ISSUE THREAD

**Issue by Mikanebu** [datahq/frontend-functional-tests#10]
We want to move back all tests using from mocha to ava. so we will be consistent about using one testing framework for all our projects.

## Acceptance criteria

* [x] All tests use `ava` testing framework

## Tasks 

* [x] move back to use `ava`

**Comment by zelima** [comment]
@Mikanebu can you move back this to mac-os and open separate issue for moving back to Linux, so we can close this one

**Comment by Mikanebu** [comment]
@zelima ok

**Comment by Mikanebu** [comment]
FIXED, tests moved back to `ava`. For moving back to `Linux`, there is separate issue https://github.com/datahq/frontend-functional-tests/issues/16
